name: Automated dev builds

on:
  push:
    branches:
      - 'ver/**'
      - 'feat/**'

jobs:
  devbuild:
    uses: duzos/mod-ci/.github/workflows/devbuild.yml@v1
    secrets: inherit
    with:
      java: '17'
      targets: >-
        [{"project":"fabric","label":"FABRIC","avatar":"https://wiki.tf2classic.com/w/images/b/b3/Engineer_BLU.png"},
         {"project":"forge","label":"FORGE","datagen":true,"avatar":"https://wiki.tf2classic.com/w/images/b/b3/Engineer_RED.png"}]
