name: Publish (CurseForge only)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false

jobs:
  publish:
    uses: duzos/mod-ci/.github/workflows/publish.yml@v1
    secrets: inherit
    with:
      targets: '[{"project":"fabric"},{"project":"forge","datagen":true}]'
      java: '21'
      task: 'publishCurseforge'
      dry_run: ${{ inputs.dry_run }}
