name: Automated dev builds

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  fabric:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Build Fabric
        run: ./gradlew -p fabric build


      - name: Publish FABRIC artifacts
        uses: DrTheodor/discord-webhook-upload-action@v1.2
        with:
          url: ${{ secrets.DEV_BUILDS }}
          file: 'fabric/build/libs/*'
          username: FABRIC builds
          avatar: 'https://wiki.tf2classic.com/w/images/b/b3/Engineer_BLU.png'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)'
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` dev build `#${{ github.run_number }}`:
            %COMMITS%
  forge:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Build Forge
        run: ./gradlew -p forge build


      - name: Publish FORGE artifacts
        uses: DrTheodor/discord-webhook-upload-action@v1.2
        with:
          url: ${{ secrets.DEV_BUILDS }}
          file: 'forge/build/libs/*'
          username: FORGE builds
          avatar: 'https://wiki.tf2classic.com/w/images/b/b3/Engineer_RED.png'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)'
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` dev build `#${{ github.run_number }}`:
            %COMMITS%