name: Publish (CurseForge only)

on:
  workflow_dispatch:

jobs:
  fabric:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Fabric
        run: ./gradlew -p fabric build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog-file: CHANGELOG.md
          curseforge-id: 845992
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

          github-generate-changelog: true
          version-type: release

          loaders: fabric
          java: 17
          files: fabric/build/libs/!(*-@(dev|sources|javadoc)).jar

  forge:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Restore DataGen cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: forge/src/generated
          key: datagen-${{ github.run_id }}
          restore-keys:
            datagen-

      - name: Run DataGen
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Save DataGen cache
        uses: actions/cache/save@v4
        with:
          path: forge/src/generated
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Build Forge
        run: ./gradlew -p forge build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog-file: CHANGELOG.md
          curseforge-id: 845992
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

          github-generate-changelog: true
          version-type: release

          loaders: forge
          java: 17
          files: forge/build/libs/!(*-@(dev|sources|javadoc)).jar
