name: Publish to Modrinth & Curseforge

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  fabric:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Build Fabric
        run: ./gradlew -p fabric build


      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.2
        with:
          changelog-file: CHANGELOG.md
          curseforge-id: 845992                                             #The id of your CurseForge project
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: 1RSY6DQH                                             #The id of your modrinth project
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-generate-changelog: true
          version-type: release

          loaders: fabric
          java: "${{env.JAVA_VERSION}}"
  forge:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Build Forge
        run: ./gradlew -p forge build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.2
        with:
          changelog-file: CHANGELOG.md
          curseforge-id: 845992                                             #The id of your CurseForge project
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: 1RSY6DQH                                             #The id of your modrinth project
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-generate-changelog: true
          version-type: release

          loaders: forge
          java: "${{env.JAVA_VERSION}}"