name: Sync README_nohtml.md

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - README.md

jobs:
  nohtml:
    uses: duzos/mod-ci/.github/workflows/sync-nohtml.yml@v1
    permissions:
      contents: write
    with:
      modules: '["."]'
